// SPDX-License-Identifier: AGPL-3.0-only
// Generated by openapi-typescript from kineuro/nils contracts/openapi/v3/openapi.yaml; do not edit.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * What this engine is and speaks (C26)
     * @description The engine version, the contract versions (openapi, review-item, pack), the loaded packs with their versions, the registry id, epoch and schema version, the auth mode, the caller's principal, roles, display name, mail, ceiling and actor, the node, the list of doors, and since version 3 `assist` (the assistant's URL when one is installed), `event_streams` (the cap), `idempotency` (the header, the doors, the hours) and `policy` (one row per door, Wave 4c section 6.5).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The capabilities */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The registry, the running jobs, the last batches (nils status --json) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The status document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/custody": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Every store the registry keeps (nils custody --json) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The custody document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The audit log, newest first (nils audit list --json) */
    get: {
      parameters: {
        query?: {
          principal?: string;
          /** @description An action */
          action?: string;
          /** @description An ISO stamp */
          since?: string;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {count, rows} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The jobs not over, newest first (nils jobs list) */
    get: {
      parameters: {
        query?: {
          /** @description The finished ones too */
          all?: boolean;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {count, jobs} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /**
     * Queue a command line for a worker (nils jobs enqueue)
     * @description The one way anything heavy runs through the door. The verb is one of digest, fingerprint, classify, pick, release, handover; the caller's principal is carried to the verb.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @description The command line without the leading nils */
            command: string[];
            name?: string;
          };
        };
      };
      responses: {
        /** @description {job, state: queued} */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not a verb the door queues */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One job with its state, progress, error and command line (nils jobs show) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The job, with its args (the queuing principal, roles, may_project_raw and actor of an ask job) and, once done, its result: for an ask run the handle, hash, grain, row_count, content_hash and truncated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such job */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/jobs/{id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ask a running job to stop at its next heartbeat, or drop a queued one (nils jobs cancel) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {job, state} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such job */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/releases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The releases the registry holds, newest first (nils release --history) */
    get: {
      parameters: {
        query?: {
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {count, releases} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Release a dataset, as a queued job (nils release) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            name: string;
            /** @description The directory to write */
            out: string;
            /** @enum {string} */
            layout?: "descriptive" | "bids";
            /** @enum {string} */
            dates?: "keep" | "shift" | "year";
            on_unknown?: string;
            pack?: string;
            scheme_name?: string;
            /** @description Codes or identifiers (Wave 4a section 8) */
            subjects?: string[];
            sessions?: string[];
            cohorts?: string[];
            /** @description axis=value */
            axes?: string[];
            stacks?: number[];
            observations?: string[];
          };
        };
      };
      responses: {
        /** @description {job, state: queued, command} */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/handovers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Hand a release over, as a queued job (nils handover run) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            release: string;
            out: string;
            key?: string;
          };
        };
      };
      responses: {
        /** @description {job, state: queued, command} */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/select": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** What a selection reaches, without releasing it (nils select); the bounded synchronous path */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            cohorts?: string[];
            subjects?: string[];
            sessions?: string[];
            stacks?: number[];
            axes?: {
              [key: string]: unknown;
            };
            /** @default mri */
            pack?: string;
          };
        };
      };
      responses: {
        /** @description {items, selection, unresolved, reaches} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description An item that cannot be read */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The review items, newest first (nils review list) */
    get: {
      parameters: {
        query?: {
          status?: string;
          kind?: string;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {count, items}; each item is contracts/review-item v2 */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/review/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One review item with its members (nils review show) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The item */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such item */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/review/{id}/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply a decision to an item (nils review apply), the one verb of the spine (Wave 4a section 10.2) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            value?: string;
            /** @description The axis has no value here */
            nothing?: boolean;
            /** @description One member of a grouped item */
            member?: number;
            /**
             * @default stack
             * @enum {string}
             */
            scope?: "stack" | "series" | "subject" | "origin";
            /** @default false */
            stage?: boolean;
            /**
             * @default person
             * @enum {string}
             */
            author_kind?: "person" | "agent" | "model";
            model_version?: string;
            why?: string;
          };
        };
      };
      responses: {
        /** @description {decision, axis, scope, ref, closed, members, staged} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Refused */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/review/{id}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Acknowledge an item without a decision (nils review accept) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            why?: string;
          };
        };
      };
      responses: {
        /** @description {review_item, accepted_by} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/decisions/{id}/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Put a staged decision in force (nils review commit) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @description Even though the registry moved on since it was staged */
            anyway?: boolean;
          };
        };
      };
      responses: {
        /** @description {committed, items} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description The registry moved on */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/decisions/{id}/withdraw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Take a decision out of force and reopen what it closed (nils review withdraw) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {withdrawn, reopened} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Already withdrawn */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Server-sent events with the open jobs and the epoch, every second, for display */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description text/event-stream: an event hello, then jobs events */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/schema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The ask's schema, generated and hand tightened, with its digest (Wave 4b section 4.5) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {generated, tightened, digest} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The catalog the caller may see, every level's first page (Wave 4b section 9) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The catalog document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/catalog/{level}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One level's fields, paged inside the published byte budget */
    get: {
      parameters: {
        query?: {
          /** @description The path the previous page ended on */
          after?: string;
        };
        header?: never;
        path: {
          level: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {level, fields, next, total} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Strict validation, or repair then validation under mode repair (Wave 4b section 4.4 rule 14) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            document?: Record<string, never>;
            /** @enum {string} */
            mode?: "strict" | "repair";
          };
        };
      };
      responses: {
        /** @description {hash, warnings, pinned, repairs} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description {error, issues}: the taxonomy errors with their paths and next calls */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * The bounded path, inside the caps (Wave 4b section 11.5): a handle with its first page of rows
     * @description The document, or a document handle, with a name for the handle, keep, after, limit and purpose; a capped run is flagged truncated and has no hash. Identifiers are projected only by a role that may read them, with an audit row.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            document?: Record<string, never>;
            document_id?: number;
            name?: string;
            keep?: boolean;
            after?: number;
            limit?: number;
            purpose?: string;
          };
        };
      };
      responses: {
        /** @description {handle, hash, columns, rows, truncated, pages, measures, drift, kept, identifiers, declaration}; the declaration (Wave 4c section 6.4) names the grain, the session scheme and its digest, the membership reading, the key namespace, the pick rule, the denominator, the disclosure and whether a cap truncated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description The document is refused */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description The role may not project identifiers */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** The unbounded path, 202 with a job id; the handle is the job's result */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            document?: Record<string, never>;
            document_id?: number;
            name?: string;
            keep?: boolean;
          };
        };
      };
      responses: {
        /** @description {job, document, state} */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/explain": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Both SQL texts and the columns, selections inlined (Wave 4b section 11.1) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {hash, sqlite, postgres, params, columns, inlined} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** A set's typed moves with stable ids, templates and legal fillers; no query (Wave 4b section 10) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            document?: Record<string, never>;
            document_id?: number;
            set?: string;
          };
        };
      };
      responses: {
        /** @description The options */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply moves by id to a document handle, atomically; a handle comes back, never a document */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            document_id: number;
            epoch: number;
            token: string;
            set: string;
            moves: unknown[];
          };
        };
      };
      responses: {
        /** @description {document, parent, hash, epoch, changed, options} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description stale_options: the list came from another document, epoch or scope */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/diagnose": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** The issues, the funnel, the drops, the ties, the coarse rows, the cost class, a zero row explanation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            document?: Record<string, never>;
            document_id?: number;
            keys?: boolean;
          };
        };
      };
      responses: {
        /** @description The diagnosis */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ten rows, or the count, by level */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {level, columns, rows, truncated} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/describe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** One sentence per set, the conventions, the denominators, the mechanisms, the disclosure */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The description */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Store a document and get its handle */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {document, hash, digest} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/documents/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A document by handle */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The document with its provenance */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such document */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/selections/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A selection's current version, or one named as name@version */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The version with its document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such selection */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Save a document as the next version of a selection (reviewer; Wave 4b section 8.2) */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {id, name, version, hash, epoch} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description The name is a cohort's */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/handles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The result handles this caller may open, newest first, within the caller's scope (Wave 4c section 7.4) */
    get: {
      parameters: {
        query?: {
          /** @description Include the withdrawn handles */
          withdrawn?: boolean;
          /** @description At most this many */
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {count, handles: [{id, name, grain, row_count, content_hash, principal, actor, created_at, epoch, pack_version, disclosure, truncated, limit, kept, last_read_at, withdrawn_at, ask_hash, columns}]} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/handles/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A result handle with its provenance */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The handle */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description The handle holds fields beyond this role's scope (Wave 4c section 6.1) */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such handle */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/handles/{id}/rows": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One page of a handle's rows, within the caller's scope, audited (Wave 4c section 6.1) */
    get: {
      parameters: {
        query?: {
          page?: number;
          /** @description Why */
          purpose?: string;
        };
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {handle, page, pages, columns, rows} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description The handle holds fields beyond this role's scope */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such page */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/handles/{id}/promote": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Promote a subject handle into a cohort, as a job (operator; Wave 4b section 8.3) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            cohort: string;
            create?: boolean;
            reason?: string;
          };
        };
      };
      responses: {
        /** @description {job, state} */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/values": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** An identifier upload, resolved through the linkage store on arrival; the shape comes back, never a value */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            namespace: string;
            values: string[];
          };
        };
      };
      responses: {
        /** @description {upload_id, namespace, n, unresolved, subjects} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/rebuild": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rebuild the session cache for a scheme, as a job under the writer (operator; Wave 4b section 7) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            scheme_name?: string;
            force?: boolean;
          };
        };
      };
      responses: {
        /** @description {job, state} */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/guide": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * What a caller is told before it writes a document (Wave 4c section 6.4)
     * @description The pack's grounding rules and worked examples, the content version, the schema digest, the door list and the caps in force; one source for both transports.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {grounding, examples, content_version, schema_digest, policy, caps} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authored text with add only repair (Wave 4c section 6.4)
     * @description A document as YAML or JSON text; the structural repairs are applied and reported, the diagnosis says what is wrong in domain words, and a valid document is stored and answered by handle. The engine never parses a sentence.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            text: string;
          };
        };
      };
      responses: {
        /** @description {repairs, diagnosis, document, hash} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/diff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * One diff over the canonical form (Wave 4c section 6.4)
     * @description Two documents answer the structural diff, set by set and part by part, with both canonical texts; two handles answer by content hash, and refuse by name when either is truncated.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @description {document} | {document_id} | {handle} */
            a: Record<string, never>;
            b: Record<string, never>;
          };
        };
      };
      responses: {
        /** @description {same, canonical_a, canonical_b, changes[{set, part, kind, before, after}]} or {same, a, b} or {same: null, refused, a, b} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ask/catalog/{level}/{field}/values": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * What a field holds, sampled under the caller's scope (Wave 4c section 6.4)
     * @description A grouped count; values with counts for a technical or clinical field, shapes (digits 9, lower a, upper A, cut at forty) for a quasi-identifying, sensitive or identifying one, the distinct count either way.
     */
    get: {
      parameters: {
        query?: {
          /** @description At most options_values */
          limit?: number;
        };
        header?: never;
        path: {
          level: string;
          field: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {level, field, kind, items[[value_or_shape, count]], distinct, truncated} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such level or field in this scope */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/packs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The loaded packs (Wave 4c section 6.5) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {packs[{name, version, contract}]} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/packs/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One pack, as nils pack show prints it (Wave 4c section 6.5) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The pack document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such pack */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The ingest batches, newest first (Wave 4c section 6.5) */
    get: {
      parameters: {
        query?: {
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {count, batches[{id, root, started_at, finished_at, counts}]} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/batches/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One batch with its report, samples as shapes only (Wave 4c section 6.5) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The batch and its report */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such batch */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/quarantine": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The quarantined files by batch and class (Wave 4c section 6.5) */
    get: {
      parameters: {
        query?: {
          batch?: number;
          class?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {count, files} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/classify/signals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The classifier's own signals over a scope (Wave 4c section 6.6; reviewer)
     * @description Per axis over a batch, an origin or a pack version, how many stacks resolved at each tier, the confidence spread, the open review items by kind, the shadowed keywords, the unused overlay terms, and the terms that carried the most decisions that disagreed with the rules.
     */
    get: {
      parameters: {
        query: {
          /** @description batch:<id> | origin:<name> | pack:<version> */
          scope: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The signals */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/classify/try": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** A candidate overlay rehearsed over a sample, writing nothing (Wave 4c section 6.6; reviewer) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            overlay: Record<string, never>;
            scope: string;
            sample?: number;
          };
        };
      };
      responses: {
        /** @description {moves[{axis, from, to, stacks}], review_items{close, open}, cases{passed, failed}} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/overlays": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The overlay objects (Wave 4c section 6.6) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {overlays[{id, name, version, status, scope, author, actor}]} */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Propose an overlay as a registry object, with a review item beside it (Wave 4c section 6.6; reviewer) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            name: string;
            overlay: Record<string, never>;
            scope: string;
            try_ref?: string;
            why?: string;
          };
        };
      };
      responses: {
        /** @description {overlay, review_item, status: proposed} */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/overlays/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One overlay with its try result (Wave 4c section 6.6) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The overlay */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No such overlay */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/overlays/{id}/adopt": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Adopt a proposed overlay and queue a reclassify over its scope (Wave 4c section 6.6; operator) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description {job, overlay, status: adopted} */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description A lower author than the one who decided */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ingest/probe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Candidate identity rules probed over a sample of a pre-registered ingest location, as a job, shapes only (Wave 4c section 6.6; operator) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            location: string;
            sample?: number;
            rules: Record<string, never>[];
          };
        };
      };
      responses: {
        /** @description {job, state}; the job's result carries, per candidate, the shape histogram of each source, identity_constant with its shape, how many files each source answered, fell through or failed to parse, the subject and study counts, and the reader's diagnostics; never a value, never a path */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: {
    /** @description A downgrade only role ceiling (Wave 4c section 5.5); it can only remove roles and is recorded on what the call touches. */
    ceiling: "reader" | "reviewer" | "operator" | "admin";
    /** @description A JSON object naming who acts for the principal: {kind: person|agent|model, name, model, version, conversation}; recorded on the audit row, the handle and the decision, with {kind: absent} as its own value when the header is missing. */
    actor: string;
    /** @description On run, jobs, apply and promote, per principal, for a day; a repeat of the same body is answered again with deduplicated true, a different body under the same key is refused 409 (Wave 4c section 6.3). */
    idempotency: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
